In [1]:
import numpy as np
from math import factorial
def combinations(n, k):
    return int(factorial(n) / (factorial(k) * factorial(n - k)))

### №1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [4]:
kov1 = np.mean(zp*ks)-np.mean(zp)*np.mean(ks) ### вычесляем ковариацию по математической формуле
kov1

9157.839999999997

In [5]:
np.corrcoef(zp,ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [6]:
np.cov(zp,ks,ddof=1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [7]:
np.cov(zp,ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [8]:
zp_std1 = np.std(zp)                      ### среднеквадратичное отклонение смещенное
zp_std2 = np.std(zp, ddof=1)              ### несмещенное
ks_std1 = np.std(ks)                    ### смещенное
ks_std2 = np.std(ks, ddof=1)             ### несмещенное

In [9]:
Pirson_ne = 10175.37777778/(zp_std2*ks_std2)
Pirson_ne

0.88749009207411

In [10]:
Pirson_sm =  9157.84/(zp_std1*ks_std1)
Pirson_sm

0.8874900920739162

### №2

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [11]:
arr = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
arr

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [12]:
M = arr.mean()  # среднее выборочное
M

118.1

In [13]:
S = np.std(arr, ddof=1)
S

10.54566788359614

In [14]:
# Используем t критерий, поскольку сигма не известна
a = 0.95
n = 10
M = 118.1
t = 2.262   # (p-a)/2 = 0.025, v =n-1 = 9, по таблице 2.262

left = M - (t*(S/(n**0.5)))
left

110.55660776308164

In [15]:
right = M + (t*(S/(n**0.5)))
right

125.64339223691834

In [16]:
# доверительный интервал [110.56; 125.64]

### №3

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [17]:
M = 174.2
std = 25**0.5
n =27
##(p-a)/2 = 1.96 - по таблице
z = 1.96
left = M-z*(std/(n**0.5))
left

172.31398912064722

In [18]:
right = M+z*(std/(n**0.5))
right

176.08601087935276

In [ ]:
# доверительный интервал [172.31; 176.09]