In [18]:
import numpy as np

### №1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [19]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [20]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [21]:
b = (np.mean(X*y)-np.mean(X)*np.mean(y))/(np.mean(X**2)-np.mean(X)**2)
b

2.620538882402765

In [22]:
a = np.mean(y)-b*np.mean(X)
a

444.1773573243596

In [23]:
y= 444.17+2.62*X
y

array([535.87, 562.07, 941.97, 968.17, 548.97, 627.57, 585.65, 837.17,
       758.57, 732.37])

In [24]:
### используем intercept

In [25]:
import seaborn as sns

In [26]:
X = X.reshape((10,1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [27]:
y = y.reshape((10,1))
y

array([[535.87],
       [562.07],
       [941.97],
       [968.17],
       [548.97],
       [627.57],
       [585.65],
       [837.17],
       [758.57],
       [732.37]])

In [28]:
X = np.hstack([np.ones((10,1)), X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [29]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T@y)
B

array([[444.17],
       [  2.62]])

In [30]:
### значения a и b такие же как при расчете без intercept

### №2

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept)

In [31]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [32]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [34]:
def mse_(B1, y=y, X=X,n=10):
    return np.sum((B1*X-y)**2)/n
alpha = 1e-6
alpha

1e-06

In [38]:
B1 = 0.1
n=10
for i in range(10):
    B1-=alpha*(2/n)*np.sum((B1*X-y)*X)
    print('B1={}'.format(B1))

B1=0.25952808
B1=0.414660650906144
B1=0.5655188230595969
B1=0.7122203698240712
B1=0.8548798195302346
B1=0.9936085448867542
B1=1.1285148499277806
B1=1.2597040545647504
B1=1.387278576808517
B1=1.5113380127259965


In [39]:
B1 = 0.1
n=10
for i in range(3000):
    B1-=alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%500==0:
        print('Iteration = {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=mse_(B1)))

Iteration = 0, B1=0.25952808, mse=493237.7212546963
Iteration = 500, B1=5.889815595583751, mse=56516.858416040064
Iteration = 1000, B1=5.8898204201285544, mse=56516.85841571941
Iteration = 1500, B1=5.889820420132673, mse=56516.85841571943
Iteration = 2000, B1=5.889820420132673, mse=56516.85841571943
Iteration = 2500, B1=5.889820420132673, mse=56516.85841571943


In [40]:
mse_(1.0)

385920.1

### №3

В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

Таблицу Лапласа мы используем, когда известна дисперсия (σ),  таблица Стьюдента - когда  сигма не известна