### №1

Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов.
Даны значения роста в трех группах случайно выбранных спортсменов:
Футболисты: 173, 175, 180, 178, 177, 185, 183, 182.
Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180.
Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [1]:
import numpy as np

In [2]:
n1 = 8
n2 = 9
n3 = 11
n = n1+n2+n3
print(n)

28


In [6]:
k = 3 # всего три группы

In [7]:
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182], dtype=np.float64)
y1

array([173., 175., 180., 178., 177., 185., 183., 182.])

In [8]:
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180], dtype=np.float64)
y2

array([177., 179., 180., 188., 177., 172., 171., 184., 180.])

In [9]:
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170], dtype=np.float64)
y3

array([172., 173., 169., 177., 166., 180., 178., 177., 172., 166., 170.])

In [13]:
### Найдем средний рост для каждой группы
y1_mean = np.mean(y1)
print(y1_mean)

179.125


In [14]:
y2_mean = np.mean(y2)
print(y2_mean)

178.66666666666666


In [15]:
y3_mean = np.mean(y3)
print(y3_mean)

172.72727272727272


In [16]:
y_all = np.concatenate([y1, y2, y3])
y_all

array([173., 175., 180., 178., 177., 185., 183., 182., 177., 179., 180.,
       188., 177., 172., 171., 184., 180., 172., 173., 169., 177., 166.,
       180., 178., 177., 172., 166., 170.])

In [18]:
y_mean = np.mean(y_all)  ### средний рост среди всех спортсменов
print(y_mean)

176.46428571428572


In [19]:
### Найдем S2 - сумму квадратов отклонений наблюдений от общего среднего
S2 = np.sum((y_all-y_mean)**2)
S2

830.9642857142854

In [20]:
### Найдем S2(F) - сумму квадратов отклонений срдених групповых значений от общего среднего 
S2_F = ((y1_mean-y_mean)**2)*n1 +((y2_mean - y_mean)**2)*n2 + ((y3_mean - y_mean)**2)*n3
S2_F


253.9074675324678

In [21]:
### Найдем S2(Ост) - остаточную квадратов отклонений
S2_residual = np.sum((y1-y1_mean)**2)+np.sum((y2-y2_mean)**2)+np.sum((y3-y3_mean)**2)
S2_residual

577.0568181818182

In [22]:
### Удостоверимся что соблюдается равенство  S2 = S2(F) + S2(ост)
print(S2)
print(S2_F+S2_residual)

830.9642857142854
830.964285714286


In [23]:
### Найдем общую дисперсию 
sigma2_general = S2/(n-1)
sigma2_general

30.776455026455015

In [24]:
###Найдем факторную дисперсию
sigma2_f = S2_F/(k-1)
sigma2_f

126.9537337662339

In [25]:
### Найдем остаточную дисперсию
sigma2_residual = S2_residual/(n-k)
sigma2_residual

23.08227272727273

In [26]:
### Вычислим F(h)
F_H = sigma2_f/sigma2_residual
F_H


5.500053450812598

In [ ]:
### Найдем значение F Крит в таблице критич точек ФИшера-Снедекора для a=0.05 и 2 степеней свободы D(межд) = K-1 = 2 и D(внутр) =  n-k = 28-3=25
  #### Для данных значений  FКрит = < 3.59 (есть данные только для D(внутр) = 17 = 3,59 и далее значение снидается при росте DВнутр)
    
    ### Поскольку Fкрит < f_h, то различие в росте статически значимо